// Auto-generated route definitions
// This file is generated by wayfinder during development

export const home = '/';
export const dashboard = '/dashboard';
export const accounts = '/accounts';
export const transactions = '/transactions';
export const ledger = '/ledger';
export const payments = '/payments';
export const admin = '/admin';
export const login = '/login';
export const register = '/register';
export const logout = '/logout';
